Comando,Posicao,Direcao,Sensor Esquerdo,Sensor Frente,Sensor Direito,Compartimento
LIGAR,"(0, 3)",2,PAREDE,VAZIO,PAREDE,SEM CARGA
INFO,"(0, 3)",2,Iniciando busca pelo humano,SEM CARGA
A,"(1, 3)",2,VAZIO,PAREDE,VAZIO,SEM CARGA
G,"(1, 3)",3,PAREDE,VAZIO,VAZIO,SEM CARGA
A,"(1, 2)",3,PAREDE,VAZIO,PAREDE,SEM CARGA
A,"(1, 1)",3,VAZIO,PAREDE,PAREDE,SEM CARGA
G,"(1, 1)",0,PAREDE,PAREDE,VAZIO,SEM CARGA
G,"(1, 1)",1,PAREDE,VAZIO,VAZIO,SEM CARGA
G,"(1, 1)",2,VAZIO,VAZIO,PAREDE,SEM CARGA
A,"(2, 1)",2,PAREDE,VAZIO,PAREDE,SEM CARGA
A,"(3, 1)",2,VAZIO,PAREDE,PAREDE,SEM CARGA
G,"(3, 1)",3,PAREDE,PAREDE,VAZIO,SEM CARGA
G,"(3, 1)",0,PAREDE,VAZIO,VAZIO,SEM CARGA
G,"(3, 1)",1,VAZIO,VAZIO,PAREDE,SEM CARGA
A,"(3, 2)",1,PAREDE,VAZIO,PAREDE,SEM CARGA
A,"(3, 3)",1,PAREDE,VAZIO,PAREDE,SEM CARGA
A,"(3, 4)",1,PAREDE,VAZIO,PAREDE,SEM CARGA
A,"(3, 5)",1,PAREDE,PAREDE,VAZIO,SEM CARGA
G,"(3, 5)",2,PAREDE,VAZIO,VAZIO,SEM CARGA
A,"(4, 5)",2,PAREDE,VAZIO,PAREDE,SEM CARGA
A,"(5, 5)",2,PAREDE,VAZIO,VAZIO,SEM CARGA
A,"(6, 5)",2,PAREDE,HUMANO,PAREDE,SEM CARGA
INFO,"(6, 5)",2,"Humano encontrado, iniciando coleta",SEM CARGA
ERRO,"(6, 5)",2,"Erro ao executar comando P: Tentativa de coleta sem humano a frente! Tentativa de mover para ({nova_i}, {nova_j})",SEM CARGA
ERRO,"(6, 5)",2,"Tentativa de coleta sem humano a frente! Tentativa de mover para ({nova_i}, {nova_j})","Traceback (most recent call last):
  File ""C:\Users\Victus\Desktop\Segundo Semestre 2024\Serviços Cognitivos\new_ads1\robo_resgate.py"", line 35, in executar_resgate
    self.coletar_humano()
  File ""C:\Users\Victus\Desktop\Segundo Semestre 2024\Serviços Cognitivos\new_ads1\robo_resgate.py"", line 146, in coletar_humano
    self.executar_comando('P')
  File ""C:\Users\Victus\Desktop\Segundo Semestre 2024\Serviços Cognitivos\new_ads1\robo_resgate.py"", line 187, in executar_comando
    self.simulador.mover_robo(comando)
  File ""C:\Users\Victus\Desktop\Segundo Semestre 2024\Serviços Cognitivos\new_ads1\simulador_labirinto.py"", line 82, in mover_robo
    raise ValueError(""Tentativa de coleta sem humano a frente! Tentativa de mover para ({nova_i}, {nova_j})"")
ValueError: Tentativa de coleta sem humano a frente! Tentativa de mover para ({nova_i}, {nova_j})
",SEM CARGA
ERRO_FATAL,"(6, 5)",2,"Tentativa de coleta sem humano a frente! Tentativa de mover para ({nova_i}, {nova_j})","Traceback (most recent call last):
  File ""C:\Users\Victus\Desktop\Segundo Semestre 2024\Serviços Cognitivos\new_ads1\main.py"", line 24, in main
    robo.executar_resgate()
  File ""C:\Users\Victus\Desktop\Segundo Semestre 2024\Serviços Cognitivos\new_ads1\robo_resgate.py"", line 35, in executar_resgate
    self.coletar_humano()
  File ""C:\Users\Victus\Desktop\Segundo Semestre 2024\Serviços Cognitivos\new_ads1\robo_resgate.py"", line 146, in coletar_humano
    self.executar_comando('P')
  File ""C:\Users\Victus\Desktop\Segundo Semestre 2024\Serviços Cognitivos\new_ads1\robo_resgate.py"", line 187, in executar_comando
    self.simulador.mover_robo(comando)
  File ""C:\Users\Victus\Desktop\Segundo Semestre 2024\Serviços Cognitivos\new_ads1\simulador_labirinto.py"", line 82, in mover_robo
    raise ValueError(""Tentativa de coleta sem humano a frente! Tentativa de mover para ({nova_i}, {nova_j})"")
ValueError: Tentativa de coleta sem humano a frente! Tentativa de mover para ({nova_i}, {nova_j})
",SEM CARGA
